services:
  postgres:
    image: postgres:15
    restart: always
    container_name: incubation_pg
    environment:
      POSTGRES_DB: incubation_pg
      POSTGRES_USER: callmekayadmin
      POSTGRES_PASSWORD: localadminpassword
    ports:
      - "5432:5432"
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data
    #   - ./scripts/:/docker-entrypoint-initdb.d/

volumes:
  postgres_data:

networks:
  shared-net:
